# Generated by Django 3.2.9 on 2021-11-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=255, verbose_name='Статья')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
